### ISSUE TITLE
[Question] fetch all the cards that are created

### ISSUE THREAD

**Issue by SanskarSans** [stripe/react-stripe-js#101]
I am totally new to stripe. I have not tried it yet. Before trying to implement stripe in my application, I wanted to know if I can fetch all the cards saved to stripe server. My use case is, user will be able to save credit cards from their profile. When they want to pay for the service, they will be shown a list of their credit cards if they have saved from the profile and can select any card they want to use for payment by just clicking on pay button without again filling card information. If they have not saved card info previously then they will fill the data manually and pay it. 

Can anyone make it clear so i can decide if I want to use stripe or not, please?

**Comment by hofman-stripe** [comment]
Hi @SanskarSans ,

This sounds like an integration question rather than an issue specific to this project (React binding for Stripe.js). For integration assistance, please reach out to [Stripe Support](https://support.stripe.com). 

That said, you may find the following integration guides to be helpful:

* [Learn how to save card details and charge your customers later.](https://stripe.com/docs/payments/save-and-reuse)
* [Learn how to save card details during a payment.](https://stripe.com/docs/payments/save-and-reuse)
