### ISSUE TITLE
Accept a Payment - Documentation on github and on Stripe website

### ISSUE THREAD

**Issue by jmitchell33** [stripe/react-stripe-js#102]
The first link under Getting Started - "Learn how to accept a payment" on Stripe's GitHub page goes through creating a client secret PaymentIntent on the backend, sending that to the frontend, and executing the payment with this client secret.  The handleSubmit ultimately ends up with this:

```
 const result = await stripe.confirmCardPayment('{CLIENT_SECRET}', {
      payment_method: {
        card: elements.getElement(CardElement),
        billing_details: {
          name: 'Jenny Rosen',
        },
      }
    });
```

Great, so then you scroll down a little and look at the main example on the GitHub page  - and the handleSubmit method does it a totally different way.

```
const payload = await stripe.createPaymentMethod({
      type: 'card',
      card: cardElement,
      billing_details: {
        name,
        address: {
          postal_code: postal,
        },
      },
    });

```

There's no mention of confirmCardPayment, this createPaymentMethod payload comes out of the blue - and generally nothing that is included in the 'Learn how to accept a payment' link.  

Why the differences?  Which should we be following?  Is one of these methods going to be deprecated?  I feel like nothing I ever read in the Stripe documentation agrees with what I read in another part of the Stripe documentation.

**Comment by dweedon-stripe** [comment]
Hi @jmitchell33,

Sorry for the late reply. This is pretty confusing. We didn't originally include the `confirmCardPayment` example because we were worried about users being confused about `{CLIENT_SECRET}` with no context. We wanted to provide something that users could copy and paste and then tweak from there. That said, we've heard this feedback quite a bit and we'll look into updating the readme to use `confirmCardPayment` with some light explanation about PaymentIntent client secrets.

Oh, and we aren't planning to deprecate either of these methods. In fact, under the hood `confirmCardPayment` actually makes a PaymentMethod for you.
