### ISSUE TITLE
Unable to update publishable key from component.

### ISSUE THREAD

**Issue by tar-aldev** [stripe/react-stripe-js#106]
Feature request or idea? Consider opening an
[API review](https://github.com/stripe/react-stripe-js/tree/master/.github/API_REVIEW.md)!

### Summary

Use case:
I am using Elements context at the very top of the app.
```
<Elements stripe={null}>
  <Router>
   <SomePage />
  </Router>
</Elements>
```

**The issue**
I have no publishable key at the startup time. Actually publishable keys are dynamic in our app and come from backend.
So I get it on my `SomePage` page.
Is there any possible way to call `stripe.createPaymentMethod(paymentInfo);` and update stripe promise with received publishable key?

I guess this my be useful in many cases, as publishable keys ay be dynamic.

**Comment by hofman-stripe** [comment]
First, is there a reason you cannot include the `Elements` provider component in `SomePage` instead of at the root of your application?

The `Stripe` instance is tied to the publishable key, there is no way to update it. You'll have to create the `Stripe` instance after you receive the key from your backend.

```js
const stripe = (async () => {
  const key = await fetchPublishableKey();
  return loadStripe(key);
})();
```

If the key can change dynamically, you'll probably have to memoize this to avoid re-creating `Stripe` objects, which is expensive. Also the `stripe` prop of the `Elements` provider cannot change once set, which means that switching instances will require you to mount a new `Elements` component. You can do that by setting a `key` prop on `Elements` so that react doesn't try to re-use the existing component instance.

If you have more questions regarding your integration, please reach out to [Stripe Support](https://support.stripe.com).
