### ISSUE TITLE
Apple Pay via PaymentRequestButton not working on connected accounts

### ISSUE THREAD

**Issue by dpicky** [stripe/react-stripe-js#112]
Apple Pay doesn't work when using a connected account

Stripe is initialised as follows
```
const stripePromise = loadStripe(process.env.STRIPE_PUBLIC_KEY, {
  stripeAccount: siteData.stripeAccount,
});

const pr = stripe.paymentRequest({.......
```

However `canMakePayment()` returns a null result

Works with card payments and Google Pay.  Also works when using a connected account in test mode just not in live mode.

I've validated that the connected account has Apple Pay enabled with the correct domain added.  I've also ran the following curl command to make sure
```
curl https://api.stripe.com/v1/apple_pay/domains \
  -u sk_live_*****: \
  -H "Stripe-Account: acct_****" \
  -d domain_name="peazi.app"
```

**Comment by hofman-stripe** [comment]
For Apple Pay and connected accounts, the connected account must also register the domains for Apple Pay.

Since this is not an issue related to this library, I will close the issue.  Please reach out to [Stripe Support](https://support.stripe.com) if you have further questions regarding your integration.
