### ISSUE TITLE
Incorrect field validation on CardNumberComponent

### ISSUE THREAD

**Issue by poteirard** [stripe/react-stripe-js#115]
### Summary

We realized that by using this specific card number: **1234 5909 8765 4320** the _onChange_ listener for the _CardNumberComponent_ receives `error: undefined, complete: true` so it's not showing an error.

However, after submitting the form I receive the following error _onSubmit_:

```
code: "incorrect_number"
doc_url: "https://stripe.com/docs/error-codes/incorrect-number"
message: "Your card number is incorrect."
param: "number"
type: "invalid_request_error"
```

Here’s a screenshot to make it more visible:

<img width="1178" alt="image001" src="https://user-images.githubusercontent.com/7198934/88539989-83f3c080-d012-11ea-9c24-f364cee5f69d.png">

**Comment by dweedon-stripe** [comment]
Hi @poteirard,

This happens because card number passes our static checks (the number is luhn valid). In this case, we can not know that the card number is invalid until we send it to our servers and try to create a payment method with it. There is always a chance that form submission will fail (e.g. card is declined). You will need to make sure that your payment form handles submission errors in addition to client-side validation errors. 

Hopefully that clears things up!

**Comment by poteirard** [comment]
Hello @dweedon-stripe,

Thank for your answer. My form already handles submission errors however I had this in the code:
```ts
if (error.type === 'validation_error' || error.type === 'invalid_request_error') {
          // We want to only show the errors in every field that's why we stop the execution
          return;
        }
```
The reason for this is because when I submit the form it triggers the client-side validations and also the submission errors.

So for example, if I have an error in the CVV I will get 2 errors: 

<img width="1604" alt="Zopa" src="https://user-images.githubusercontent.com/7198934/88645021-f1135e80-d0c3-11ea-842a-4a171dcd508a.png">

Is this the expected behaviour? Shall I show duplicated errors?

Thank you
