### ISSUE TITLE
How to update a paymentmethod listener for paymentRequest button

### ISSUE THREAD

**Issue by matt-dalton** [stripe/react-stripe-js#126]
### Summary
We're using a Stripe PaymentRequestButton, and would like to update the purchased product based on a selection on the page.

The docs provide a way of updating the [payment request object](https://stripe.com/docs/js/payment_request/update) itself, and this allows the user to see the new amount reflected in the browser payment UI.

However, we're using an on paymentmethod listener to implement some server-side logic that actually carries out the payment:

```
paymentRequest.on('paymentmethod', async ev => {
      serverRequestFunction(paymentDetailObject) //
} 
```

This listener will always be set with the previous product options, so the purchase will go through incorrectly. I have tried running this again on update, but then you end up with two listeners.

Is there a way of changing this listener? Or even removing it so we can add a new one? Or any other workarounds?

Thanks

### Other information

Tested in Chrome v84
@stripe/react-stripe-js 1.1.2
@stripe/stripe-js 1.7.0

**Comment by asolove-stripe** [comment]
Hi @matt-dalton! Sorry for the confusion here. I would recommend you either wait and attach this event listener when the customer clicks on the payment request button, or else add a layer of indirection so that your event handler can read the product data from wherever it is stored (redux? a component? whatever state management you use) and then use that data in handling the event.

**Comment by ckimjin** [comment]
hello @matt-dalton, it seems that we will still have the same issues of having multiple event listeners because lets say an API call in the 'paymentmethod' listener fails for some reason and we close the Apple Pay UI. The user could re-click the CTA that will reopen the Apple Pay UI which in turn creates additional event listeners if we attach the event listeners on click.

**Comment by Kuhreez** [comment]
This is not in the official documentation from what I can tell, but I was able to find a way to remove any duplicate listeners.

You can call `paymentRequest .removeAllListeners()` to remove all existing listeners and then reattach a listener of your choice. I believe this removes all callbacks from the `paymentRequest` though, which may not be the desired behavior if you have other listeners such as on click, or on token.

You can also check to see if the `paymentRequest` object already has a listener of a certain type attached to it, and just remove that specific listener in that case.
```
if (paymentRequest.hasRegisteredListener('paymentmethod')) {
  paymentRequest.off('paymentmethod');
}

paymentRequest.on('paymentmethod', ...);
```

You can either do this on click as [asolove-stripe](https://github.com/asolove-stripe) has suggested, or in my case I did it in a `useEffect` when some of my payment details are mutated. Both methods seem to work.

I know this is an old thread, but I hope this helps anyone else who stumbles upon this thread

**Comment by firatgh** [comment]
@Kuhreez Thanks for sharing your cents. I am facing the same issue.

**Comment by bobmccracken** [comment]
Yeah this is a closed issue, but it has helped me 2 years after the fact. A similar issue was raised in the old repo that deals with the same problem: https://github.com/stripe-archive/react-stripe-elements/issues/526. FWIW, @christopher-stripe indicated they were planning on updating docs with the `off` method.

My thanks to @Kuhreez as well for providing a comprehensive answer.
