### ISSUE TITLE
PaymentRequestButton doesn't set cardholder_name when `requestPayerName: true`

### ISSUE THREAD

**Issue by matheusazzi** [stripe/react-stripe-js#142]
Hello. Not sure if it's a bug or intended behavior, I'm initializing the PaymentRequest with:
`{ requestPayerName: true, requestPayerEmail: true }`

Then upon `paymentmethod` event I can trigger the purchase completion.
```ts
objPaymentRequest.on(
  'paymentmethod',
  async (event: PaymentRequestPaymentMethodEvent) => {
    console.log(event.paymentMethod) // <- token
  }
)
```

However, it seems Stripe doesn't use `payerName` when tokenizing that payment method, I'd expect that happens when using `requestPayerName`. Looking at Stripe Dashboard, that customer has no Billing details, but their name was asked on the browser's Payment Dialog.

Is there a way I can update the payment method on that `on('paymentmethod',` callback and set `billingDetails.name`?

**Comment by dweedon-stripe** [comment]
Hi @matheusazzi, 

Sorry for the late reply. This does seem like a bug and I’ve filed it in our internal tracker and will post updates here if we anything to share. In the meantime, we’re going to close out this GitHub issue because this issue tracker is for bugs with React Stripe.js specifically.

As a workaround you could listen for a `token` and use the token and the returned billing details to create a `PaymentMethod` manually:

```js
objPaymentRequest.on('token', async (event: PaymentRequestPaymentMethodEvent) => {
  await stripe.createPaymentMethod({
    type: 'card',
    card: { token: event.token.id },
    billing_details: { name: event.payerName },
  });
});
```

If you are using `confirmCardPayment` you can actually do the same there as well:
```js
await stripe.confirmCardPayment(clientSecret, {
  payment_method: {
    card: { token: event.token.id },
    billing_details: { name: event.payerName },
  },
});
```
