### ISSUE TITLE
Flex Functionality for CardElement

### ISSUE THREAD

**Issue by charliemday** [stripe/react-stripe-js#149]
### Summary

Wrapping the `CardElement` in any FlexBox seems to hide the component. Is there functionality for this as wrapping components in a FlexBox is quite a common pattern? 

I believe the issue is caused by not allowing any flex value in the options prop of the `CardElement`

### Other information

Code Sandbox for Example (line 15 - remove the `display: flex` to show the `CardElement`): 
https://codesandbox.io/s/lucid-nobel-578y7?file=/src/App.js

**Comment by christopher-stripe** [comment]
Setting a `flex-basis` for the child flex Element will fix this. So instead of:

```jsx
<div style={{display: 'flex'}}>
  <CardElement />
</div>
```

it would be:

```jsx
<div style={{display: 'flex'}}>
  <div style={{flexBasis: '100%'}}>
    <CardElement />
  </div>
</div>
```

Rendering a `CardElement` renders a wrapper `div` around an inner secure `iframe`. The `iframe` reads the width of the wrapper `div` to size itself. A `div` with the default `display: block;` value will fill the size of its parent, so the inner iframe will then expand to the parent size as expected. But in this case, setting `display: flex;` caused the wrapper `div` to expand to the size of the child iframe, which is initially 0.
