### ISSUE TITLE
How to set iDeal Banks List height

### ISSUE THREAD

**Issue by samouds** [stripe/react-stripe-js#151]
Hello,

I have an issue with the IdealBankElement, the banks list is too big for my parent iframe. I can't reach the bottom of the list.

<img width="313" alt="Screenshot 2021-01-19 at 23 46 45" src="https://user-images.githubusercontent.com/4284515/105103581-1e5c2a80-5ab1-11eb-9749-c52504571cd5.png">

The height of the list is always 207px (calculated automatically I guess), but it's too high. There is any way to change it ?

PS. the form is in an iframe.

Thanks.

**Comment by dweedon-stripe** [comment]
Hi @samouds,

Sorry, for the late reply. Unfortunately, this isn't really configurable today. We’ve filed this as a feature request in our internal tracker and will post updates here if we anything to share. In the meantime, I'm going to close out this GitHub issue because this issue tracker is for bugs with React Stripe.js specifically.
