### ISSUE TITLE
Not compatible with `React.StrictMode`

### ISSUE THREAD

**Issue by baristikir** [stripe/react-stripe-js#256]
### Summary
My application is running on a `React@18-rc`version and was facing some issues with the `Elements` api. The hooks `useStripe` and `useElements` return values were `null` when using `React.StrictMode`. Also the `PaymentElement` component did never show up when it was in the tree of `React.StrictMode`.

```ts
const stripePromise = loadStripe("pk_...")
export function PaymentForm() {
	return (
		<React.StrictMode>
			<Suspense fallback={<Spinner />}>
				<Elements stripe={stripePromise} options={{ clientSecret: "" }}>
                                     <CheckoutForm />
                                </Elements>
			</Suspense>
		</React.StrictMode>
	);
}

const CheckoutForm = () => {
   const stripe = useStripe(); // only equals null when wrapped around Recat.StrictMode
   const elements = useElements(); // only equals null when wrapped around Recat.StrictMode

   return (
     <PaymentElement id="payment-element" /> // never shows up in React.StrictMode tree
   )
}
```

For my case I was using Next.js (version: `next@12.0.8`) and had the reactStrictMode enabled in the `next.config.js`. By disabling it in the next config, it all worked as expected. The code is a small repro of it.

**Comment by christopher-stripe** [comment]
Hi @baristikir, React Stripe.js is indeed not compatible with StrictMode.

We've made an effort to support StrictMode in the past, only to find additional breaking restrictions later added to StrictMode that we could not anticipate. StrictMode warns about usage patterns that won't work well with experimental concurrent features in React, but since plans for concurrent React are a moving target so is StrictMode support.

Our current thinking is that we intend to support stable React features as soon as they are released. This may require publishing a breaking major version of React Stripe.js, which we want to avoid if possible. Hence we don't intend to track experimental React features that may never become stable
