### ISSUE TITLE
Card Element - only takes 3 digits of the CVC number with American Express cards

### ISSUE THREAD

**Issue by johan1113** [stripe/react-stripe-js#263]
### Summary

Hi Stripe team!

We were trying to implement a payment process with the CardElement component from `react-stripe-js` and we found the next issues:

<img width="866" alt="image" src="https://user-images.githubusercontent.com/26172313/157740229-5ff91879-e968-4fc6-8e2f-d1579319da12.png">
<img width="858" alt="image" src="https://user-images.githubusercontent.com/26172313/157740338-38b96840-6016-479b-9196-231f5daddfac.png">
<img width="863" alt="Captura de Pantalla 2022-03-10 a la(s) 2 32 08 p m" src="https://user-images.githubusercontent.com/26172313/157741873-1970fd15-6c0f-48d1-89db-65fdcb092bfa.png">

As you can see above, we implemented a real time verification for the CardElement that works fine with all cards except for Amex cards. Currently we can generate tokens for Amex cards with only 3 CVC digits instead of 4 and we are afraid of can't restrict this for users trying to submit Amex cards.

### Other information

<img width="465" alt="image" src="https://user-images.githubusercontent.com/26172313/157741855-181b38f6-dc75-4266-a55a-671d0f04e75b.png">

We were using onChange callback from CardElement to generate quick verifications with the `stripe.createToken` method, and it only triggers until the third CVC digit is reached (the onChange method is not triggered when you try to type the fourth CVC digit).

PD: We would like to know too if maybe is a better way to implement the validation of the credit card, in special for Amex Cards.

Thank you all Stripe Team!

**Comment by bmathews-stripe** [comment]
Hi @johan1113! 

We don't emit onChange events for every input or key press, only when an _exposed_ value or state of the element changes. 

Because the CVC field is private and both 3 and 4 digit values are in the 'potentially complete' status, you aren't receiving an onChange event for that 4th digit.

This behavior isn't a good fit for your intended use case, unfortunately. We'll keep your use case in mind as we continue to improve these APIs.

In the mean time, please reach out to [Stripe Support](https://support.stripe.com/) for suggestions on building an integration that meets your UX goals!
