### ISSUE TITLE
className prop changes remove the StripeElement classes from the wrapping DOM node

### ISSUE THREAD

**Issue by dackmin** [stripe/react-stripe-js#267]
### Summary

The `StripeElement` class (and any corresponding `--<state>` sibling class) is removed from the parent dom node when the `className` prop of the component changes after the first render (for example using the famous `classNames()`.
I think this is due to the fact that this class is managed from within the SDK itself instead of react. So when the `className` prop changes and React re-renders, classes added by the elements SDK (whether it's using `.className` or `.classList`) are coming from outside and are not part of the equation, so they're simply removed.

### Other information

Both components should have the same styles but if any class on the first one changes after the first render, it's becomes as raw as [insert random porn joke]:
![Capture d’écran 2022-03-23 à 17 39 45](https://user-images.githubusercontent.com/1873323/159751170-83f8206e-068e-456c-ab48-68ef6edd00ca.png)

But as soon as I focus/blur the field, as the elements SDK comes into play, it finds its magic again:
![Capture d’écran 2022-03-23 à 17 39 52](https://user-images.githubusercontent.com/1873323/159751277-3c69c462-9ac0-48bc-b5c9-bc48b96b8f02.png)

It acts the same way on every browser, but for what it's worth:
- Chrome 99.0.4844.74
- React 17.0.2

Even if I could achieve this with a wrapping element taking care of the changing classes, I'd rather do this with the component itself, as `className` is supposed to behave like this.

**Comment by tylersmith-stripe** [comment]
Hey @dackmin 👋 ,

Can you provide a code sample for the above example? It'd be helpful to see your JSX DOM tree, and the initial `className` state.

**Comment by dackmin** [comment]
Of course, sorry: https://codesandbox.io/s/eager-https-qkmv31?file=/src/App.js

**Comment by tylersmith-stripe** [comment]
Got it, tysm for the repo! I can definitely see the issue now, and will bring this internally for the team to review and hash out a solution.

We'll post status updates here in this ticket as we progress on a fix.

**Comment by tylersmith-stripe** [comment]
We're continuing to look into solutions for this, alongside React 18 support investigations.

**Comment by dackmin** [comment]
stale[bot] stop being who you are
@tylersmith-stripe any updates on this? I found @christopher-stripe's PR clever, but I guess it's a bit too hacky to be merged.

**Comment by christopher-stripe** [comment]
Hey @dackmin, the solution in #271 does indeed feel a bit too hacky to merge. I think the core issue (that both the React wrapper and Stripe.js itself want to manage the `class` attribute) is unlikely to be solved without changing the API of React Stripe.js itself. In particular, I think that React Stripe.js should either create its own wrapping `<div>`, or not support the `className` prop.

That said, I also don't think that this is enough of an issue to warrant pushing a fix and publishing React Stripe.js 2.0 today. Perhaps when we have other breaking changes we want to release, we can bundle this fix along with those.

To workaround this issue in the meantime, I think there are two options. The first is to create a separate wrapping div for your React managed styles. So instead of:

```jsx
<CardNumberElement className={classNames('input', { disabled })} />
```

Do this instead:

```jsx
<div className={classNames('input', { disabled })}>
  <CardNumberElement  />
</div>
```

The other alternative is to not set the class via the `className` prop, but to use the [Stripe.js classes option](https://stripe.com/docs/js/elements_object/create_element?type=card#elements_create-options-classes) instead. I don't think this will work for your specific use case since there is no class option for the `disabled` state, but it could help with other states (complete, invalid, etc.)

**Comment by dackmin** [comment]
Thanks, yep that's what I was doing before trying to remove the seemingly-useless parent div and remembering why it was there in the first place 😄  Closing this issue and looking forward to v2!
