### ISSUE TITLE
colorTextTerms variable not supported

### ISSUE THREAD

**Issue by benschwarz** [stripe/react-stripe-js#270]
When reviewing logs reported by our app using stripe.elements, I noticed the following error: 

```
Using stripe.elements(): invalid variable "colorTextTerms"; "colorTextTerms" is not a supported variable.
```

In checking the documentation, `colorTextTerms` is still mentioned in the "Less commonly used variables" section. 

Preview: Our variables within the appearance option: 

<img width="433" alt="image" src="https://user-images.githubusercontent.com/924/160961481-ebf16152-a264-4b70-91ff-5ca5762f4e7f.png">

Is `colorTextTerms` still an available option?

**Comment by tylersmith-stripe** [comment]
Hi @benschwarz 👋,

Sorry, that is a documentation mistake on our side! The target you're looking for is the `.TermsText` selector in `rules`. By default, `.TermsText` uses `colorTextSecondary`, which you could set here instead of `colorTextTerms`:

```
{
  variables: {
    colorTextSecondary: colors.grey300
  }
}
```

Or, if you don't want to use this for all components that leverage `colorTextSecondary`, you can target `.TermsText` directly:

```
{
  rules: {
    '.TermsText': {
      color: colors.grey300
    }
}
```

Thank you for reporting this issue in our [Appearance API docs](https://stripe.com/docs/stripe-js/appearance-api#additional-variables) - we'll get that fixed straight away!

**Comment by benschwarz** [comment]
Hey @tylersmith-stripe, thanks for the heads up. I've updated our implementation ⚡

**Comment by tylersmith-stripe** [comment]
@benschwarz the docs have been updated to correct this mistake. Thank you again for flagging, and do let us know if you run into any other documentation issues!
