### ISSUE TITLE
Support Selective Use of Stripe

### ISSUE THREAD

**Issue by babalugats76** [stripe/react-stripe-js#28]
### Summary

Will this project address the long-standing issue of **not being able to truly selectively and dynamically use Stripe in React**?

Heretofore, developers have been forced to live with **persistent controller iframes** and **event listeners** throughout their SPA unless they want to develop their own **custom hacks** to delete upon component dismount.

It would be great if this library somehow **included the logic to remove** all elements, dependencies, etc., from the DOM, etc.

I am intrigued by this project, but I don't see the point, if it doesn't address what is arguably **developers' top bugaboo**.  I don't understand why this has been ignored for so long.

### Other information

Refer to [https://github.com/stripe/react-stripe-elements/issues/99](https://github.com/stripe/react-stripe-elements/issues/99) for additional context.

Developers have shared countless JavaScript hacks to "clean up" after stripe.  In the end, developers are trying to remove these iframes (and related event listeners):

![stripe-controller-inspector](https://user-images.githubusercontent.com/6919889/73467180-34248d00-4340-11ea-8a38-7efded810e4d.png)

I am submitting this issue at the request of stripe engineers on **freenode**.  I would definitely tag this as a **question**.

**Comment by dweedon-stripe** [comment]
Hi @babalugats76,

I understand that this is painful and raises concerns about the privacy of your users. @asolove-stripe provides an [overview of why these frames exist](https://github.com/stripe/react-stripe-elements/issues/99#issuecomment-528987443) in the original issue.

This new library should solve some of the problems outlined in the linked issue. Unlike `react-stripe-elements`, this library does not create an instance of `Stripe` for you. You should not see an ever increasing number of `__privateStripeController` frames.

We do plan to address the issue of lingering iframes in the core Stripe.js library; it is not specific to React or this wrapper. Since this cannot be addressed from this library, I am going to close this issue.
