### ISSUE TITLE
[BUG]: Can't find variable: PaymentAutofillConfig

### ISSUE THREAD

**Issue by abrenaut** [stripe/react-stripe-js#302]
### What happened?

Hi,

We are using the react-stripe-js library to take payments on our web application using the Stripe PaymentIntent API.

We've recently started seeing the following error in our Sentry logs:

```
ReferenceError

Can't find variable: PaymentAutofillConfig

in getValuesOfAutofillInputs at line 36:13444
```

This is only happening on iOS from the Instagram browser and was first seen on the 2nd of June 2022.

### Environment

Instagram 238.0.0 on iPhone iOS 15.5

**Comment by jackieosborn-stripe** [comment]
Hi @abrenaut! This doesn't appear to be coming from Stripe.js code (can't find any mention of `PaymentAutofillConfig` or `getValuesOfAutofillInputs` in our code 🙂). It seems likely that it has to do with a plugin, or Instagram itself.

If you still believe it's an issue with Stripe.js, please reach out to [Stripe Support](https://support.stripe.com/) so that we can track and prioritize this issue internally.  [React Stripe.js](https://github.com/stripe/react-stripe-js) is a wrapper around the underlying Stripe.js script, so we don’t track those issues here.

**Comment by abrenaut** [comment]
Thanks @jackieosborn-stripe , will do, I'll also follow [this thread on StackOverflow](https://stackoverflow.com/questions/72488297/referenceerror-getvaluesofautofillinputs-cant-find-variable-paymentautofillco) where people seem to have a similar issue.
