### ISSUE TITLE
[BUG]: Uncaught IntegrationError: card Element didn't mount normally. 

### ISSUE THREAD

**Issue by timsayshey** [stripe/react-stripe-js#316]
### What happened?

I'm getting this Stripe error from our app: "Uncaught IntegrationError: card Element didn't mount normally." 

My app is a Web Component, is that not supported? Are there workarounds?

You can see the error here when you click on an image and the pop up with the Stripe form loads:
https://app.ecardwidget.com/widget/5150

![image](https://user-images.githubusercontent.com/1148940/187328659-7ec30274-8e1a-479e-ae33-acf68ec374a1.png)

### Environment

Chromium: 104.0.5112.81 on MacOS

### Reproduction

https://app.ecardwidget.com/widget/5150

**Comment by jackieosborn-stripe** [comment]
Hi @timsayshey! This error usually occurs if the Element is mounted inside a shadow DOM tree, or somehow isn't reachable. For more assistance, I would recommend reaching out to [Stripe Support](https://support.stripe.com/contact) or chatting with us in the [Stripe Discord](https://discord.com/invite/stripe) for help, as the Stripe Support team is much better equipped to provide a complete and timely answer to your question.

I'm going to close out this issue since we only track issues with the React Stripe.js wrapper itself here.
