### ISSUE TITLE
[BUG]: need to show card holder and billing text field in element 

### ISSUE THREAD

**Issue by MzkZeeshan** [stripe/react-stripe-js#319]
### What happened?

i thought need to add props in stripe Element that can show some text field like cardholder name , billling address......!

**Comment by jackieosborn-stripe** [comment]
Hi, it looks like this is a question about how to integrate with Elements. The Stripe Support team is much better equipped to provide a complete and timely answer these types of questions, so I would recommend reaching out to them at [Stripe Support](https://support.stripe.com/contact) or in the [Stripe Discord](https://discord.com/invite/stripe).

I'm going to close out this issue since we only track issues with the React Stripe.js wrapper itself here.
