### ISSUE TITLE
[BUG]: Google / Apple Pay button doesn't appearing with slow internet

### ISSUE THREAD

**Issue by dimylkas** [stripe/react-stripe-js#329]
### What happened?

Problem with using the `PaymentRequestButtonElement` and` createPaymentRequest.canMakePayment()`, for slow internet, from time to time returns `null` and buttons doesn't appears. A refreshing browser may fix the issue, but not always. For a normal connection, everything is ok.

Issue easily reproducible also at https://stripe.com/docs/stripe-js/elements/payment-request-button , just turn on the "Slow 3G" 
![image](https://user-images.githubusercontent.com/22882779/195213343-af10d910-c590-4ce1-9d00-9b47e2d8a7e8.png) at the browser, and you'll see the issue.

### Environment

Chrome Version 105.0.5195.125 (Ubuntu 18)

**Comment by graceg-stripe** [comment]
Hi @dimylkas, this is the intended behavior rather than a bug. We will timeout checking for the payment availability after 10 seconds, and mark it as unavailable. It's possible for slower internet to not return any results within 10 seconds, in which case Google/Apple Pay button will not render on the page.
