### ISSUE TITLE
[BUG]: Input field for smaller screens

### ISSUE THREAD

**Issue by Lexpeee** [stripe/react-stripe-js#332]
### What happened?

Yo. Any way we can fit the entire input box contents for smaller devices?
![image](https://user-images.githubusercontent.com/30643024/195722469-5ac403eb-4f54-4774-90de-911822567353.png)

**Comment by jackieosborn-stripe** [comment]
Hi @Lexpeee! You might find it helpful to integrate with our [split Card Element](https://stripe.com/docs/js/elements_object/create_element?type=cardNumber) (`cardNumber`, `cardExpiry`, and `cardCvc`).

Since this is an integration question, I'm going to close out this issue since we only track issues with the React Stripe.js wrapper itself here. The Stripe Support team is much better equipped to provide a complete and timely answer for these types of questions, so I would recommend reaching out to them at [Stripe Support](https://support.stripe.com/contact) or in the [Stripe Discord](https://discord.com/invite/stripe) if you need any additional help.
