### ISSUE TITLE
[BUG]: Apple Pay was use to request a payment, the payment interface was showing however it was immediately closing

### ISSUE THREAD

**Issue by mytabworks** [stripe/react-stripe-js#343]
### What happened?

When the Apple Pay was use to request a payment, the payment interface was showing however it was immediately closing without finishing the process... and not event triggering the event listener **"paymentmethod"** or **"cancel"**

I just implemented what was on this docs 100% [docs](https://stripe.com/docs/stripe-js/elements/payment-request-button?client=react)

any thoughts what was missing? or I've done something wrong?

### Environment

iOS 14 safari

**Comment by jima-stripe** [comment]
Sorry to hear this is isn't working @mytabworks.

To better help understand what the issue is, can you help me answer a few questions?
* Using the same device you're seeing the issue with, click the Apple Pay button on the docs page that you link. Does the payment interface work as expected or does it also immediately close?
* Are you getting any errors/warnings/messages in your console that you could share?
* Are you able to share the code you wrote?

**Comment by mytabworks** [comment]
@jima-stripe I appreciate your quick response, you are awesome!

1. Yes the payment interface doesn't work as expected. it close immediately in a blink of an eye..
2. no error and warning just closed immediately, or rather I can't see it since Iam using iOS
3. what I wrote was just a copy paste of the docs though 

`import React, {useState, useEffect} from 'react';
import {PaymentRequestButtonElement, useStripe} from '@stripe/react-stripe-js';

interface PayButtonProps {
    country?: string,
    currency?: string,
    totalAmount: number;
    totalLabel: string;
    requestPayerName?: boolean;
    requestPayerEmail?: boolean;
    onSupported?: (supported: boolean) => void;
    onPayment: (event: any) => void;
}

const PayButton: React.FunctionComponent<PayButtonProps> = ({
    country,
    currency,
    totalAmount,
    totalLabel,
    requestPayerEmail,
    requestPayerName,
    onSupported,
    onPayment
}) => {
    const stripe = useStripe();
    const [paymentRequest, setPaymentRequest] = useState<any>(null);

    useEffect(() => {
        if (stripe && !paymentRequest && totalAmount) {
            const pr = stripe.paymentRequest({
                country: country!,
                currency: currency!,
                total: {
                    label: totalLabel,
                    amount: Number(totalAmount) * 100,
                },
                requestPayerName: requestPayerName,
                requestPayerEmail: requestPayerEmail
            });

            // Check the availability of the Payment Request API.
            pr.canMakePayment().then(result => {

                if(onSupported) {
                    onSupported(!!result)
                }

                if (result) {
                    setPaymentRequest(pr);
                }
            })
        }
    }, [stripe]);

    useEffect(() => {
        if(paymentRequest) {
            paymentRequest.on('paymentmethod', onPayment)
    
            return () => {
                paymentRequest.off('paymentmethod', onPayment);
            }
        }
    }, [paymentRequest, onPayment])

    if (paymentRequest) {
        return <PaymentRequestButtonElement options={{paymentRequest}} />
    }

    // Use a traditional checkout form.
    return null;
}

PayButton.defaultProps = {
    country: 'GB',
    currency: 'gbp',
    requestPayerName: true,
    requestPayerEmail: false
}

export default PayButton

`

**Comment by mytabworks** [comment]
@jima-stripe also as you can see on the code I need to x 100 the amount... I wonder why is that? when putting the real amount... it was showing on the payment interface was like divided by 100... that is why i need to x 100 to show on payment interface the real value

**Comment by jima-stripe** [comment]
The `amount` property expects the total amount represented in cents. So $1 would `amount: 100`. You can read more about that here: https://stripe.com/docs/js/appendix/payment_item_object#payment_item_object-amount

In terms of the issue with the payment sheet disappearing, I suspect there is a configuration issue with your phone since it's failing on the docs page, too. We're not getting widespread reports of an issue that might suggest otherwise.

Generally, an error like you're seeing would suggest some kind of configuration error. Apple would likely log a message to the console that would help identify the root cause. If you're not familiar with accessing console logs from iOS Safari, you can check out this [article](https://www.lifewire.com/activate-the-debug-console-in-safari-445798).

If you can provide the error message from the console, I can help take a look at what might be going on.

Keep me posted.

**Comment by mytabworks** [comment]
@jima-stripe my apple pay account is actually working properly on the docs page... and I also check the console in safari on iOS and it has no error found...

do you think I have something wrong with the iOS prerequisite configuration? because I am currently using it on many subdomain it might be the issue?

**Comment by mytabworks** [comment]
It is now been sorted out thanks

[Solution](https://stackoverflow.com/questions/74474115/stripe-apple-pay-immediately-closing)
