### ISSUE TITLE
[BUG]: React.createContext is not a function

### ISSUE THREAD

**Issue by OllieJW** [stripe/react-stripe-js#352]
### What happened?

When using Stripe elements trying to make a subscription form, I get the error `React.createContext is not a function`. I can't find any solution to this anywhere.

The same code works in React but not Next (version 13)

### Reproduction

https://codesandbox.io/s/beautiful-swartz-fuu6sc?file=/src/App.js

**Comment by martinalong-stripe** [comment]
Hi @OllieJW! I wasn't able to see any place where you're calling `React.createContext` or anything related to Stripe in that code sandbox.

This seems like a bug related to React and not Stripe though, from what I can tell, since there's no reason stripe should interfere with React. To confirm, you could comment out any code that uses stripe and see if you still experience the issue.

**Comment by OllieJW** [comment]
Seems like the issue was because my form elements were inside a component. Putting them straight into the file fixed this

**Comment by martinalong-stripe** [comment]
Fantastic!
