### ISSUE TITLE
[BUG]: PAY button doesnt works on codesandbox

### ISSUE THREAD

**Issue by salimbenfarhat** [stripe/react-stripe-js#353]
### What happened?

Hello, when i open the codesandbox demo and i add my test stripe key. When I type CB test card 4242 4242 4242 4242 01/25 123 and validate by clicking on "Pay" CTA. Nothings appears on my dashboard stripe. Is it normal ?

### Environment

_Desktop - Win10 OS - Brave Browser_

**Comment by salimbenfarhat** [comment]
![Capture](https://user-images.githubusercontent.com/28115417/205266809-4e115704-85a0-46c2-8347-56e3d50a42cf.PNG)

**Comment by martinalong-stripe** [comment]
Hi @salimbenfarhat, it looks like a lot of the demos use [stripe.createPaymentMethod](https://stripe.com/docs/js/payment_methods/create_payment_method) which doesn't actually confirm the payment, just records the payment method. So since no payment happened, you wouldn't see it in your dashboard. 

If you are in need of an integration example, [this guide](https://stripe.com/docs/payments/card-element#complete-payment) is probably a better place to look, and has a downloadable project to reference!

**Comment by salimbenfarhat** [comment]
Thank you
