### ISSUE TITLE
[BUG]: `CardElement` `ZIP` field shows `Postcode` instead of `ZIP`

### ISSUE THREAD

**Issue by geryit** [stripe/react-stripe-js#382]
### What happened?

We want to use [CardElement](https://stripe.com/docs/payments/card-element) on our payment page, but we see `Postcode` field, which we couldn't change. Is there a way to change it to say `ZIP`?

![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/514149/220563427-9c988c5d-75f9-4d4f-b10f-e78e06421cef.png)

**Comment by martinalong-stripe** [comment]
Hi @geryit! The placeholder for this field is determined dynamically based off the country of the card's issuing bank. So if a user enters a UK card, they'll see "Postcode" (and users will see "ZIP" for a US card and "Postal code" for a Canadian card).

It looks like this is happening because you're using the test card 4242 4242 4242 4242 in production (with live mode API keys). 4242 4242 4242 4242 is a US card in our testmode environment (ZIP), but in the actual world, the BIN 4242 42 (first 6 number of the card number) corresponds to a UK bank, hence why you see "Postcode". 

If you try a real US card number, you should see "ZIP". Or if you try this same card number, but in test mode, you should also see "ZIP"

In case you want to test out this behavior for yourself in testmode, you can find the test cards for different countries here: https://stripe.com/docs/testing#international-cards

**Comment by martinalong-stripe** [comment]
@geryit Just found out why this is btw! Apparently 4242 42 used to be a US bin, so we listed it as a US bin for testing purposes, but about 5 years ago it switched to being a GB bin. However, since a lot of our users were already using this as a US test bin, we decided to special case it in testmode. However, in livemode/reality, it is now a GB bin (hence "Postcode")

For all other test cards we have, the country should be the same in live and testmode!
