### ISSUE TITLE
[BUG]: The locale for arabic not translating cvc

### ISSUE THREAD

**Issue by Noob7** [stripe/react-stripe-js#383]
### What happened?

Im using react payment element from react-stripe 
  <Elements
      stripe={stripePromise}
      options={{ clientSecret, appearance, locale }}
    >
where locale is ar. but the rendered payment element translates other fields but skips CVC. So my entire page is in Arabic while CVC is in English. Can we please look into this

<img width="632" alt="Screen Shot 2023-02-22 at 3 49 11 PM" src="https://user-images.githubusercontent.com/10553468/220619279-20d14978-77bc-4009-a357-1c8aa0b2bd41.png">

**Comment by brendanm-stripe** [comment]
Hey @Noob7 sorry for the long silence on this while we investigated. As it turns out, this is the expected result for the `ar` locale currently due to some other limitation. We're looking at ways to improve this, and if you have a particular localization that you'd expect to see either labelling the CVC field or as a placeholder I'm happy to share that feedback internally while we evaluate.
