### ISSUE TITLE
TypeError: cyclic object value

### ISSUE THREAD

**Issue by talkingtab** [stripe/react-stripe-js#49]
```
const cardElement = elements.getElement(cardNumberElement); // split form
const payload = await stripe.confirmCardPayment(secret, {card: cardElement});

```

this results in the cyclic object value error message in the title.

```
const payload = await stripe.confirmCardPayment(secret, {});

```
does the expected thing: payload.error has a bunch of stuff

**Comment by dweedon-stripe** [comment]
Hi @talkingtab, we should definitely find a way to make that error message clearer. To fix, you need to move the `card: cardElement` into the `payment_method` hash.

```js
const payload = await stripe.confirmCardPayment(secret, {
  payment_method: {card: cardElement},
});
```

Going to close this because (aside from the very unclear error) this is actually intended, and because the fix for the unclear error will need to happen in Stripe.js rather than in this wrapper library.
