### ISSUE TITLE
[BUG]: StripeCardElement does not support cards with US issue country but CA post code

### ISSUE THREAD

**Issue by tomas-c** [stripe/react-stripe-js#501]
### What happened?

Stripe seems to use card issue country to enable/disable entry of letters, spaces or other characters in the zip code field.

If the card issue country uses numeric post codes but the card post code is not in the issue country, then users cannot enter the correct post code. We've had several customers with this issue.

It would be helpful if StripeCardElement had a flag to always allow letters, spaces or other characters in the zip code input field.

I found this old issue which was closed without a resolution: https://github.com/stripe-archive/react-stripe-elements/issues/135

**Comment by brendanm-stripe** [comment]
This is a known limitation of the Card Element that we fixed with the [Payment Element](https://docs.stripe.com/payments/payment-element), which includes a separate/explicit billing country selector for cards.

<img width="540" alt="pe-country" src="https://github.com/stripe/react-stripe-js/assets/57721954/917e5f2a-2035-4ca8-9f43-7470807ee894">

This is not something I expect to change for card element, so I would recommend using payment element instead if you can.

The workaround with Card Element requires manually implementing postal code handling. You need to:
1/ hide the postal code field ([ref](https://docs.stripe.com/js/elements_object/create_element?type=card#elements_create-options-hidePostalCode))
2/ collect country & appropriate postal code with your own form fields
3/ include country/postal in `billing_details` when you call `confirmCardPayment` ([ref](https://docs.stripe.com/js/payment_intents/confirm_card_payment#stripe_confirm_card_payment-with_element-payment_method-billing_details))
