### ISSUE TITLE
[BUG]: googlepay integration in stripe 

### ISSUE THREAD

**Issue by Saharshdiwan** [stripe/react-stripe-js#502]
### What happened?

stripe version^1.16.5  and it is not showing googlepay , i have activated googlepay in payment methods in stripe so give me solution how can i integrate googlepay in my website through stripe. Website is in react version 17.0.2 . My website only showing card payment help me in this

**Comment by brendanm-stripe** [comment]
Please contact our support team with details of your integration so that they can assist: https://support.stripe.com/contact 

Your GH profile geolocation indicates you are in India, so please be aware that Google Pay is not available for accounts or customers based in India: https://support.stripe.com/questions/supported-payment-methods-currencies-and-businesses-for-stripe-accounts-in-india
