### ISSUE TITLE
Rest operator (...) not transpiled resulting in crash in e.g Microsoft Edge

### ISSUE THREAD

**Issue by AxelJunes** [stripe/react-stripe-js#55]
### Summary
Hi, we've just migrated from react-stripe-elements to react-stripe-js and we're getting the error `Expected identifier, string or number` because of a spread operator (...).

Steps to reproduce:
* Open [Try it out using CodeSandbox](https://codesandbox.io/s/react-stripe-official-q1loc?fontsize=14&hidenavigation=1&theme=dark) in Microsoft Edge.

**Comment by dweedon-stripe** [comment]
Hi @AxelJunes, 

Sorry you ran into this. We did have a bug, but this was fixed in [v1.0.3](https://github.com/stripe/react-stripe-js/releases/tag/v1.0.3). You should be able to upgrade to the latest without needing to make any other changes.

Also, I just updated the versions in the CodeSandbox demo.

**Comment by AxelJunes** [comment]
Hi @dweedon-stripe,

Thanks for the quick response. I will upgrade it straight away.

Keep up the good work!
