### ISSUE TITLE
Safari: CardExpiry focus state does not focus input initially

### ISSUE THREAD

**Issue by danielgormly** [stripe/react-stripe-js#60]
### Summary

When I place CardNumber, CardExpiry, CardCvc individually on the page and try to tab through them, I can see the class `.StripeElement--focus` on the container element showing up, but the actual input for CardExpiry does not focus i.e. there is no caret nor can I input any text.

Weirdly if I tab backwards (shift+tab) from CardCvc, and go over the entire CardExpiry (it seems to stop 2-3 times internally) then arrive back at it, it does focus.

### Other information

- @stripe/react-stripe-js@1.0.3
- Safari Version 13.0.5 (14608.5.12)
- It does work on the latest Microsoft Edge (Webkit version)

**Comment by carawarner** [comment]
Seconded. We're experiencing the same issue as the OP when interacting with Stripe Elements in Safari 13. Importantly, **we don't see this behavior in older versions of Safari.** It's safe to say, this is probably related to a recent change in Safari. It now blocks focusing into cross-domain iframes 🤦‍♂

You might find this [support post](https://support.stripe.com/questions/ios-13-and-stripe-elements-label-focus-issue) interesting and [this issue](https://www.gitmemory.com/issue/stripe/react-stripe-elements/357/595821818) too.

**Comment by mbarrett-stripe** [comment]
Yep, sorry this is the same issue that we are aware of in https://github.com/stripe/react-stripe-elements/issues/357 (albeit the title of the issue is different. The root cause is the same).

See my response (as @carawarner linked above) [here](https://github.com/stripe/react-stripe-elements/issues/357#issuecomment-595821818). It's something we're aware of and trying to work with Apple to resolve.
