### ISSUE TITLE
Post Mortem on NPM Issue?

### ISSUE THREAD

**Issue by iMerica** [stripe/react-stripe-js#62]
Hello Stripe team,

Can we please have a post mortem on what exactly happened with `@stripe/react-stripe`? 

Yesterday I merged a massive pull request only to find out today that it was never auto deployed. The reason why the deploy never happened was because yarn got a 404 response on this package:

> error An unexpected error occurred: "https://registry.yarnpkg.com/@stripe/react-stripe-js/-/react-stripe-js-7.0.0-beta.1.tgz: Request failed \"404 Not Found\"".

I've done 75 deploys previously using this Stripe package and my yarn/package manifest never changed so I assumed this was a npm/yarn CDN hosting issue.  Upon visiting the package page on NPM, I learn that this actually been deprecated

<img width="584" alt="Screen Shot 2020-03-04 at 2 42 10 PM" src="https://user-images.githubusercontent.com/487897/75921312-887ec900-5e26-11ea-9c47-959617a8639d.png">

Moving a NPM package that relates to accepting credit cards with such brazen carelessness is extremely troubling. How am I supposed to know if Stripe's NPM account was hacked and this new NPM location is actually a compromised piece of software? This is exactly how it would happen if Stripe's account is hacked.

This sudden deprecation/rename was handled very poorly. As of right now, I still don't actually know if `@stripe/react-stripe-js` is compromised or not. Please remember: this is not just another React Component on Github/NPM. This one is responsible for dealing with payments. When you suddenly change the name of an NPM package it will creates A LOT of consternation for security-minded people.

Can someone official from Stripe please confirm this new package you're forwarding to is actually genuine and not compromised?

Thank you,

Michael

**Comment by asolove-stripe** [comment]
Hi @iMerica! I understand your concern, but want to be clear that this renaming is both not a hack and not something we will do again.

We were comfortable doing this renaming because the package was marked as an early beta and had very few downloads at the time. The name was simply wrong (there are many other react-related Stripe things, and this one is specifically for Stripe.js) and needed to be fixed. We will certainly not be doing it again, now that the package is marked as out of beta.

**Comment by dweedon-stripe** [comment]
Hi @iMerica,

I'm very sorry you ran into this. Renaming and re-versioning a package is a hack. We will not be doing it again. We decided to do it in this case because we were in an early beta and because the previous package name was misleading and wrong. There are many React based things at Stripe, we wanted to make it clear that this package was for Stripe.js specifically.

**Comment by iMerica** [comment]
Thank you for the prompt response 👍 . I've updated my package.json to use the new name/version.

**Comment by dweedon-stripe** [comment]
👍 Great! Again, very sorry you got caught up in this, it won't happen again.
