### ISSUE TITLE
Redirection of payment gateway

### ISSUE THREAD

**Issue by Abhijeetjaiswalit** [stripe/react-stripe-js#63]
```js
const result = await stripe.confirmIdealPayment(iDEALPayment.clientSecret, {
            payment_method: {
              ideal: elements.getElement(IdealBankElement),
              // billing_details: {
              //   name: 'Jenny Rosen',
              // },
            },
            return_url: window.location.href,
          });
```

i'm using this method for completing the payment. now what it really does, is it simply redirects us to the strip's payment page for completing the payment on the same page. i wanted to have more control over this default redirection.
e.g => how can we redirect the user into new tab or in the same tab but in a modal. like it does in this exapmle while using card payment.
 https://stripe.com/docs/payments/accept-a-payment

**Comment by hofman-stripe** [comment]
You could manually handle the redirect, and open the URL in a new tab. However you cannot open that URL in an iframe modal as banks do not support it.

To do so you would pass the [`handleActions: false` option to `confirmIdealPayment()`](https://stripe.com/docs/js/payment_intents/confirm_ideal_payment#stripe_confirm_ideal_payment-options-handleActions):

```js
const result = await stripe.confirmIdealPayment(iDEALPayment.clientSecret, {
            payment_method: {
              ideal: elements.getElement(IdealBankElement),
              // billing_details: {
              //   name: 'Jenny Rosen',
              // },
            },
            return_url: window.location.href,
          }, {
            handleActions: false,
          });
```

Then you can follow item 2 and 3 of the [guide's section "Handle iDEAL Redirect manually"](https://stripe.com/docs/payments/ideal/accept-a-payment#handle-redirect).

However please make sure you can still open a new tab by the time you receive the response. Most browsers blocks opening popup if the action isn't rooted in a user action.

Closing as this issue is not with this library but usage of the the Stripe SDK. Our support team is available to help with further guidance and can help you figure your integration out. You can [reach out to them here](http://support.stripe.com/email) for help.

**Comment by Abhijeetjaiswalit** [comment]
@hofman-stripe  thank you so much for your response. I did talk with stripe support, they directly said it is not possible currently. i can send you the screenshot. Thats why i came here for the query.

passing  `handleActions: false` is indeed an option. i would take the redirect uri and open it in new tab. but then after payment is done, we don't have any provision of closing the tab automatically, do we?
flow is like => click pay button(from the app) open a new tab or window for payment, complete the ayment => close the window/tab=> show the success message on the app(that is still open in the background).
