### ISSUE TITLE
Should "Elements" go at the top level of my app?

### ISSUE THREAD

**Issue by Dakkers** [stripe/react-stripe-js#69]
### Summary

Not a bug, just a question. In the examples, `Elements` goes at the very top level, similar to `StripeProvider`. Should this be the case for non-trivial applications too? Or should it go only where it is needed?

**Comment by dweedon-stripe** [comment]
It won't hurt anything to put at at the top of your app, but you can use it where you need it. You should however ensure you are [loading Stripe.js throughout your app](https://github.com/stripe/stripe-js#ensuring-stripejs-is-available-everywhere) so that you can take advantage of our fraud detection.
