### ISSUE TITLE
Multiple Stripe Keys

### ISSUE THREAD

**Issue by rmcfadzean** [stripe/react-stripe-js#75]
I have an interesting issue in on site I'm working on for a client.

They want to swap stripe PKs (and the backend will swap SKs based on the same logic) based on a number of conditions in the checkout form.

We're using @stripe/react-stripe-js at the moment (having upgraded from the old react-stripe-elements package) and I've noticed that it does not like me switching PKs on the fly. Ignoring the warning and continuing anyway, obviously, causes the wrong key to be used.

### Summary

The current flow is as follows:

* The user fills out the form (swapping PK on the client side based on their inputs) & fills out their card details
* They hit "pay"
* We generate a payment intent on the backend using the correct key for their inputs
* We try to capture it on the frontend, supposedly, using the correct key

The problem seems to be that `<Elements>` doesn't accept changes in the `stripe` prop at any point and always sticks to the first set key.

### Other information

I did some digging and found that `setContext` only ever gets set when `final` is not true. https://github.com/stripe/react-stripe-js/blob/master/src/components/Elements.tsx#L135-L148

Is there a technical reason for this? Should I be switching to Stripe Checkout?

Thanks to @w1zeman1p on IRC for the initial help.

**Comment by hofman-stripe** [comment]
The limitation is one of the underlying SDK. Stripe.js Elements are created from a `Stripe` instance, and cannot be rebound to another instance. You also cannot update the publishable key of an existing `Stripe` instance.

This library is making the check since there would be no way to perform a transparent switch of the pk.

Now you haven't detailed what input conditions cause the PK from being swapped. If this condition can be evaluated before any Stripe element has been filed, could you render the input used in evaluating the condition before rendering the `Elements` component, or resolve the `stripe` promise only once the pk value is known? If you want to have the form fully rendered from the beginning, you could recreate the `Elements` component with a new `stripe` instance instead of updating the existing component. This would cause all the elements to be re-created, and any filled values would be lost.

Since this is an integration question that is not entirely specific to React Stripe.js. Can you reach out to [Stripe support](https://support.stripe.com)? They should be able to help you figure out the best path forward.
