### ISSUE TITLE
Information about result token/id

### ISSUE THREAD

**Issue by debotos** [stripe/react-stripe-js#79]
The result or id I am getting from this(https://github.com/stripe/react-stripe-js/blob/master/examples/class-components/2-Split-Card.js) example, via using it am I able to make recurring payment?

Thanks.

**Comment by dweedon-stripe** [comment]
Hi @debotos,

This sounds like an integration question rather than an issue specific to this project (React binding for Stripe.js). For integration assistance, please reach out to [Stripe Support](https://support.stripe.com). 

That said, here are a few integration guides that might be helpful:

* [Learn how to save card details and charge your customers later.](https://stripe.com/docs/payments/save-and-reuse)
* [Learn how to save card details during a payment.](https://stripe.com/docs/payments/save-and-reuse)
* [Learn how to create and charge for a subscription.](https://stripe.com/docs/billing/subscriptions/cards)
