### ISSUE TITLE
Value prop doesn't change placeholder

### ISSUE THREAD

**Issue by nimabrownlee** [stripe/react-stripe-js#89]
I want to change the placeholder "Card number" to another language but with no success. Am I using the wrong prop or are you not able to change the placeholder?

`
const CARD_ELEMENT_OPTIONS = {
  value: 'test',
  style: {
    ...
  }
}
`

**Comment by dweedon-stripe** [comment]
Hi @nimabrownlee,

You may not need to do this. Elements will localize automatically to your customer's browser locale. If you prefer, you can also [set the locale directly](https://stripe.com/docs/js/initializing#init_stripe_js-options-locale):

```js
import loadStripe from `@stripe/stripe-js`

const stripe = loadStripe('{{PUBLISHABLE_KEY}}', {locale: 'es'})
```

If you still need to override the placeholder for the `CardNumberElement` you can do this by changing the [`placeholder`](https://stripe.com/docs/js/elements_object/create_element?type=cardNumber#elements_create-options-placeholder) option.

```js
const CARD_ELEMENT_OPTIONS = { placeholder: 'test', style: { ... } }
```

**Comment by nimabrownlee** [comment]
@dweedon-stripe 
Hey, you dont support the Swedish locale. Also I tried the placeholder prop but it didn't work. Maybe a bug?

**Comment by hofman-stripe** [comment]
The `placeholder` property is only supported for the `cardNumber`, `cardExpiry` and `cardCvc` elements, not for the combined `card` element.

**Comment by thomaslc66** [comment]
This library is crazy.

All cardnumber, cardexpiry and cardCvc can get a placeholder but not the cardElement...
But cardElement can have an icon, but not cardNumber....

So there is no way to set the placeholder in other languages based on the website language

**Comment by hofman-stripe** [comment]
@thomaslc66 which locale does your website support that isn't [supported by Elements](https://stripe.com/docs/js/appendix/supported_locales)? We're always looking for feedback on new languages to support.

Btw, the `CardNumberElement` now supports the card icon through the [`showIcon` option](https://stripe.com/docs/js/elements_object/create_element?type=cardNumber#elements_create-options-showIcon). It's named differently than other Elements `hideIcon` option since the default is for the icon to be hidden for the `cardNumber` Element.

**Comment by Crushford** [comment]
I am also having this issue with Romanian locale :)
