### ISSUE TITLE
Custom display component

### ISSUE THREAD

**Issue by IcyTv** [stripe/react-stripe-js#92]
#### Summary

I would love the ability to add custom (react) components to the stripe iframes!

#### Motivation

The motivation comes from projects like [react-credit-cards](https://github.com/amarofashion/react-credit-cards) which adds a beautiful UI to visualize credit cards. This just makes the user experience so much better!

#### Alternatives

Add the option to add [react-credit-cards](https://github.com/amarofashion/react-credit-cards) to elements

#### Scope

This would probably impact all element components.

#### Risks

I don't know much about the risks involved with this, but they shouldn't be to crazy, if the communication to the outside gets denied!

**Comment by hofman-stripe** [comment]
Unfortunately there would be no way to satisfy this request as-is in a PCI compliant way. The point of Stripe Elements is to wrap the card data in iframes so that the card info, which is subject to PCI requirements never touches the embedding website. A custom display of the card info would, by definition, need access to the info that's under PCI scope.

What might be technically possible is to create a new Element that is a "read only" live mirror of the input of another Element. With the same font customization, transparency and clever layering of DOM elements, it might be possible to replicate the experience of the referenced React component. Given the complexity however, I don't expect this to happen anytime soon, sorry.

Regardless, this is more a feature request for the base Stripe.js library and somewhat unrelated to this wrapper. I'll close this issue, but feel free to discuss further.
